function gerarMensagem(){
    const mensagens  = [
        "Acredite em si mesmo e tudo será possível.",
        "Você é mais forte do que pensa.",
        "Cada novo dia é uma nova oportunidade.",
        "O sucesso é a soma de pequenos esforços repetidos diariamente.",
        "Não tenha medo de falhar, tenha medo de não tentar.",
        "A persistência é o caminho do êxito.",
        "Acredite que você pode e você já está no meio do caminho.",
        "Você é capaz de mais do que imagina.",
        "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
        "Mantenha seus pensamentos positivos, porque seus pensamentos se tornam suas palavras.",
        "A vida é 10% o que acontece com você e 90% como você reage a isso.",
        "Grandes coisas nunca vêm da zona de conforto.",
        "O fracasso é apenas a oportunidade de recomeçar com mais inteligência.",
        "Você é o único que pode limitar sua grandeza.",
        "Acredite em você e tudo será possível.",
        "O sucesso não é definitivo, o fracasso não é fatal: o que conta é a coragem de continuar.",
        "A força não vem da capacidade física, vem de uma vontade indomável.",
        "Você nunca é velho demais para estabelecer um novo objetivo ou sonhar um novo sonho.",
        "O segredo para ir em frente é começar.",
        "Acredite no seu potencial infinito.",
        "A maior glória em viver não está em nunca cair, mas em se levantar cada vez que caímos.",
        "A chave do sucesso é se concentrar nos objetivos, não nos obstáculos.",
        "Você não é definido por suas falhas, mas como se levanta depois delas.",
        "Nunca desista, porque é exatamente esse o lugar e a hora que a maré vai virar.",
        "A coragem não é a ausência do medo, é a persistência apesar do medo.",
        "Cada pequena vitória deve ser comemorada.",
        "Transforme seus sonhos em planos e seus planos em realidade.",
        "A disciplina é a ponte entre metas e realizações.",
        "Se você quer algo que nunca teve, precisa fazer algo que nunca fez.",
        "Os desafios são o que fazem a vida interessante e superá-los é o que dá sentido à vida.",
        "O melhor ainda está por vir.",
        "Você é a única pessoa responsável pelo seu sucesso.",
        "Não deixe que o medo de perder seja maior que a emoção de ganhar.",
        "A determinação de hoje conduz ao sucesso de amanhã.",
        "Acredite, esforce-se e supere.",
        "Não se preocupe em falhar, preocupe-se em não tentar.",
        "Você tem dentro de você agora, tudo o que precisa para enfrentar o mundo.",
        "Nunca é tarde demais para ser aquilo que sempre se desejou ser.",
        "O sucesso não vem de repente, é construído dia após dia.",
        "Você é mais corajoso do que acredita, mais forte do que parece e mais inteligente do que pensa.",
        "Acredite que você pode, e você estará no meio do caminho.",
        "Não importa a velocidade, vá em frente.",
        "O impossível é apenas uma opinião.",
        "A cada dia, em cada maneira, você está melhorando mais e mais.",
        "Tudo o que você precisa está dentro de você.",
        "Quando você quer alguma coisa, todo o universo conspira para que você realize o seu desejo.",
        "A diferença entre o ordinário e o extraordinário é aquele pequeno extra.",
        "Trabalhe duro em silêncio, deixe que seu sucesso faça barulho.",
        "Acredite em milagres, mas não dependa deles.",
        "Grandes realizações não são feitas por impulso, mas por uma série de pequenas coisas reunidas.",
        "O futuro pertence àqueles que acreditam na beleza de seus sonhos.",
        "O primeiro passo para conseguir algo é desejá-lo.",
        "Não pare quando estiver cansado, pare quando tiver terminado.",
        "A única maneira de fazer um excelente trabalho é amar o que você faz.",
        "Não espere por oportunidades extraordinárias. Aproveite as ocasiões comuns e as torne grandes.",
        "A vida não é sobre encontrar a si mesmo. A vida é sobre criar a si mesmo.",
        "Faça o que você pode, com o que você tem, onde você está.",
        "O que você pensa, você cria. O que você sente, você atrai. O que você acredita, torna-se realidade.",
        "Acredite no seu valor e suas habilidades únicas.",
        "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
        "Você tem o poder de criar, melhorar e transformar.",
        "Não olhe para trás. Você não está indo nessa direção.",
        "A vida é feita de escolhas. Faça boas escolhas hoje.",
        "Nunca subestime o poder dos seus sonhos.",
        "A jornada de mil milhas começa com um passo.",
        "Concentre-se no que você quer, não no que você não quer.",
        "Mantenha-se positivo, trabalhe duro e faça acontecer.",
        "Você é o criador do seu próprio destino.",
        "Seja a mudança que você quer ver no mundo.",
        "Você é mais forte do que qualquer desafio.",
        "A vida é curta demais para esperar.",
        "Transforme suas dificuldades em oportunidades.",
        "Cada desafio é uma nova chance para crescer.",
        "Seu potencial é ilimitado.",
        "Você pode fazer coisas incríveis.",
        "Nada é impossível para um coração determinado.",
        "Você tem o poder de mudar sua vida.",
        "Seja grato pelo que você tem, enquanto persegue o que você quer.",
        "Você é capaz de superar qualquer obstáculo.",
        "Os sonhos não funcionam a menos que você trabalhe para eles.",
        "Sua atitude determina sua altitude.",
        "Cada novo dia é uma nova chance para mudar sua vida.",
        "Nunca pare de sonhar, nunca pare de acreditar.",
        "Faça cada dia valer a pena.",
        "Seja a sua melhor versão.",
        "O que você faz hoje pode melhorar todos os seus amanhãs.",
        "O único limite para nossos futuros é nossas dúvidas de hoje.",
        "Não espere pela oportunidade, crie-a.",
        "Acredite em você e todas as coisas são possíveis.",
        "O caminho pode ser difícil, mas a vista é maravilhosa.",
        "Você é capaz de realizar grandes coisas.",
        "Nunca é tarde demais para ser quem você poderia ter sido.",
        "Os melhores dias estão à sua frente.",
        "Mantenha a cabeça erguida e o coração firme.",
        "Sucesso é a soma de pequenos esforços repetidos diariamente.",
        "Não deixe ninguém roubar sua alegria.",
        "Acredite no poder dos seus sonhos.",
        "Seja audacioso, seja corajoso, seja você.",
        "Você é único e pode fazer a diferença no mundo."
    ];
    const indiceAleatorio = Math.floor(Math.random() * mensagens.length);
    document.getElementById('mensagem').innerText = mensagens[indiceAleatorio];
}
function limpar(){
    document.getElementById('mensagem').innerText = "";
}